name: Build and Push to GHCR

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify version file and extract version
        id: get_version
        run: |
          if [ ! -f vite.config.ts ]; then
            echo "vite.config.ts not found"
            exit 1
          fi

          VERSION=$(grep -oE "appVersion *= *['\"]([^'\"]+)['\"]" vite.config.ts | sed -E "s/.*['\"]([^'\"]+)['\"].*/\1/")
          if [ -z "$VERSION" ]; then
            echo "Version not found in vite.config.ts"
            exit 1
          fi

          echo "Detected VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/tma-cloud/cloud_storage-frontend:${{ env.VERSION }}
            ghcr.io/tma-cloud/cloud_storage-frontend:latest
          build-args: |
            APP_VERSION=${{ env.VERSION }}
            COMMIT=${{ github.sha }}
